default: convert

convert:
	umlet -action=convert -format=png -filename=UseCase.uxf -output=UseCase.png
	umlet -action=convert -format=png -filename=Class.uxf -output=Class.png
	umlet -action=convert -format=png -filename=Entity.uxf -output=Entity.png
